public class HelloWorldMultilingual {
    public static void main(String[] args) {
        System.out.println("Hello World!");
        System.out.println("Hallo Wêreld!");
        System.out.println("Përshendetje Botë!");
        System.out.println("ሰላም ልዑል!");
        System.out.println("مرحبا بالعالم!");
        System.out.println("Բարեւ աշխարհ!");
        System.out.println("নমস্কাৰ বিশ্ব!");
        System.out.println("¡Aski urukipanaya Uraqpacha!");
        System.out.println("Salam Dünya!");
        System.out.println("Bonjour Diɲɛ!");
        System.out.println("Kaixo Mundua!");
        System.out.println("Прывітанне Сусвет!");
        System.out.println("Shani Mwechalo!");
        System.out.println("ওহে বিশ্ব!");
        System.out.println("नमस्कार दुनिया के बा!");
        System.out.println("Zdravo Svijete!");
        System.out.println("Здравей свят!");
        System.out.println("Hola món!");
        System.out.println("ជំរាបសួរ ពិភពលោក!");
        System.out.println("Hello Kalibutan!");
        System.out.println("ᎣᏏᏲ ᎡᎶᎯ");
        System.out.println("Moni Dziko Lapansi!");
        System.out.println("世界您好!");
        System.out.println("Wawa Klahowya Hayas Klaska");
        System.out.println("Salutu Munnu!");
        System.out.println("Pozdrav Svijete!");
        System.out.println("Ahoj Světe!");
        System.out.println("Hej Verden!");
        System.out.println("ހެލޯ ވޯލްޑް!");
        System.out.println("नमस्कार दुनिया !");
        System.out.println("Hello Rhaesheser!");
        System.out.println("Hallo Wereld!");
        System.out.println("Saluton mondo!");
        System.out.println("Tere Maailm!");
        System.out.println("Mido gbe na Xexeame!");
        System.out.println("Hello Mundo!");
        System.out.println("Hei maailma!");
        System.out.println("Salut le monde!");
        System.out.println("Hallo wrâld!");
        System.out.println("Ola mundo!");
        System.out.println("გამარჯობა სამყაროს!");
        System.out.println("Hallo Welt!");
        System.out.println("Γειά σου Κόσμε!");
        System.out.println("Maitei Mundo!");
        System.out.println("હેલો વર્લ્ડ!");
        System.out.println("Bonjou mond!");
        System.out.println("Sannu Duniya!");
        System.out.println("Aloha Honua!");
        System.out.println("שלום עולם!");
        System.out.println("नमस्ते दुनिया!");
        System.out.println("Nyob zoo ntiaj teb!");
        System.out.println("Helló Világ!");
        System.out.println("Halló heimur!");
        System.out.println("Ndewo Ụwa!");
        System.out.println("Hello Lubong!");
        System.out.println("Halo Dunia!");
        System.out.println("Dia duit Domhanda!");
        System.out.println("Ciao Mondo!");
        System.out.println("こんにちは、 世界！");
        System.out.println("Halo Donya!");
        System.out.println("ಹಲೋ ವರ್ಲ್ಡ್!");
        System.out.println("Сәлем Әлем!");
        System.out.println("សួស្តីពិភពលោក!");
        System.out.println("Mwaramutse Isi!");
        System.out.println("Habari dunia!");
        System.out.println("qo' Vivan!");
        System.out.println("नमस्कार संवसार!");
        System.out.println("안녕하세요 월드입니다!");
        System.out.println("Halo Wɔl");
        System.out.println("Silav Cîhan!");
        System.out.println("سڵاو جیهان!");
        System.out.println("Салам дүйнө!");
        System.out.println("ສະບາຍດີຊາວໂລກ!");
        System.out.println("salve mundi!");
        System.out.println("Sveika Pasaule!");
        System.out.println("h3l1O W()rL|)!");
        System.out.println("Mbote Mokili!");
        System.out.println("Sveikas Pasauli!");
        System.out.println("coi li terdi!");
        System.out.println("Mwasuze Mutya Ensi!");
        System.out.println("Moien Welt!");
        System.out.println("Здраво свету!");
        System.out.println("नमस्कार दुनिया!");
        System.out.println("Manahoana izao tontolo izao!");
        System.out.println("Hai dunia!");
        System.out.println("ഹലോ വേൾഡ്!");
        System.out.println("Ħello dinja!");
        System.out.println("Kia ora te Ao!");
        System.out.println("हॅलो वर्ल्ड!");
        System.out.println("ꯍꯜꯂꯣꯏ ꯃꯥꯂꯦꯝ!");
        System.out.println("Bello Globo!");
        System.out.println("Hello Khawvel!");
        System.out.println("Сайн уу Дэлхий!");
        System.out.println("မင်္ဂလာပါကမ္ဘာလောက!");
        System.out.println("नमस्कार संसार!");
        System.out.println("Hallo Verden!");
        System.out.println("ନମସ୍କାର ବିଶ୍ୱବାସି!");
        System.out.println("Akkam jirtu Addunyaa!");
        System.out.println("!سلام نړی");
        System.out.println("!سلام دنیا");
        System.out.println("Witaj świecie!");
        System.out.println("Olá Mundo!");
        System.out.println("ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!");
        System.out.println("Hola Mundo!");
        System.out.println("Salut Lume!");
        System.out.println("Здравствуй мир!");
        System.out.println("Talofa le Lalolagi!");
        System.out.println("नमस्कार विश्व!");
        System.out.println("Halò a Shaoghail!");
        System.out.println("Thobela Lefase!");
        System.out.println("Здраво Свете!");
        System.out.println("Lefatše Lumela!");
        System.out.println("Mhoro Nyika!");
        System.out.println("هيلو دنيا!");
        System.out.println("හෙලෝ වර්ල්ඩ්!");
        System.out.println("Ahoj svet!");
        System.out.println("Pozdravljen svet!");
        System.out.println("Salaamu Calaykum!");
        System.out.println("¡Hola Mundo!");
        System.out.println("Halo Dunya!");
        System.out.println("Salamu Dunia!");
        System.out.println("Hallå världen!");
        System.out.println("Kamusta mundo!");
        System.out.println("Салом Ҷаҳон!");
        System.out.println("ஹலோ உலகம்!");
        System.out.println("Сәлам, Дөнья!");
        System.out.println("హలో వరల్డ్!");
        System.out.println("สวัสดีโลก!");
        System.out.println("ሰላም ዓለም!");
        System.out.println("Xewani Misava!");
        System.out.println("Merhaba Dünya!");
        System.out.println("Salam Dünýä!");
        System.out.println("Hello Wiase!");
        System.out.println("Привіт Світ!");
        System.out.println("ہیلو دنیا والو");
        System.out.println("ياخشىمۇسىز دۇنيا!");
        System.out.println("Salom Dunyo!");
        System.out.println("Xin chào thế giới!");
        System.out.println("Helô Byd!");
        System.out.println("Molo Lizwe!");
        System.out.println("העלא וועלט!");
        System.out.println("Mo ki O Ile Aiye!");
        System.out.println("Sawubona Mhlaba!");
    }
}
